import { Header } from '@/components/Header'
import ModalProvider from '@/providers/ModalProvider'
import SupabaseProvider from '@/providers/SupabaseProvider'
import ToasterProvider from '@/providers/ToasterProvider'
import UserProvider from '@/providers/UserProvider'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Delicias Upao',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body className={inter.className}>
        <ToasterProvider />

        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />

            <Header />

            <main className='relative mx-auto flex max-w-5xl flex-col justify-center px-4 md:px-0'>
              {children}
            </main>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
